/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruiterSimRouteImport } from './routes/recruiter-sim'
import { Route as ImprovedRouteImport } from './routes/improved'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'

const RecruiterSimRoute = RecruiterSimRouteImport.update({
  id: '/recruiter-sim',
  path: '/recruiter-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprovedRoute = ImprovedRouteImport.update({
  id: '/improved',
  path: '/improved',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/improved': typeof ImprovedRoute
  '/recruiter-sim': typeof RecruiterSimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/improved': typeof ImprovedRoute
  '/recruiter-sim': typeof RecruiterSimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/improved': typeof ImprovedRoute
  '/recruiter-sim': typeof RecruiterSimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyze' | '/improved' | '/recruiter-sim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze' | '/improved' | '/recruiter-sim'
  id: '__root__' | '/' | '/analyze' | '/improved' | '/recruiter-sim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ImprovedRoute: typeof ImprovedRoute
  RecruiterSimRoute: typeof RecruiterSimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recruiter-sim': {
      id: '/recruiter-sim'
      path: '/recruiter-sim'
      fullPath: '/recruiter-sim'
      preLoaderRoute: typeof RecruiterSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improved': {
      id: '/improved'
      path: '/improved'
      fullPath: '/improved'
      preLoaderRoute: typeof ImprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ImprovedRoute: ImprovedRoute,
  RecruiterSimRoute: RecruiterSimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
